Increase native-image PageSize to 64k
Older versions of GraalVM defaulted to compiling binaries using the
compilation hosts' page-size (typically 4k).

This results in the cljfmt binary failing to start on kernels compiled
with larger page sizes - such as the Raspberry Pi 5, and Mac running
Asahi Linux.

    Fatal error: Failed to create the main Isolate. (code 8)

Newer versions of GraalVM native-image default to a page size of 64k
which avoids producing binaries that fail to start on Linux kernels
configured for more than 4k pages.

Picking a larger build-time page size is strictly more compatible (the
runtime page size just needs to be <= the build-time value), so there's
no functional downside for 4k-page systems.